# source: https://github.com/lycheeverse/lychee-action/
# https://github.com/userbradley/documentation.breadnet.co.uk/blob/main/.github/workflows/broken-link-checker.yaml

name: Broken Link Checker
on:
  repository_dispatch:
    types: [test]
  workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *" #"00 18 * * *"
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Links
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html' './**/*.rst' --exclude-mail --exclude 'http://localhost:*/*' --exclude 'https://*.canva.com/*' --exclude 'https://*.openai.com/*' --exclude 'https://*.chatgpt.com/*' --exclude 'https://*.recharts.org/*' --exclude 'https://*.leetcode.com/*' --exclude 'https://*.igdb.com/*' --exclude 'https://*.indeed.com/*' --exclude 'https://*.konghq.com/*' --exclude 'https://*.tableau.com/*' --exclude 'https://*.careerbuilder.com/*' --exclude 'https://*.phind.com/*' --exclude 'https://*.zenrows.com/*'
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5.0.0
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: Broken Link
