name: Broken Link Checker PR
on:
  pull_request:
    types:
      - synchronize
      - opened
    paths:
      - /**
      - .github/workflows/broken-link-checker-pr.yaml
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Links
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html' './**/*.rst' --exclude-mail --exclude 'http://localhost:*/*' --exclude 'https://*.canva.com/*' --exclude 'https://*.openai.com/*' --exclude 'https://*.chatgpt.com/*' --exclude 'https://*.recharts.org/*' --exclude 'https://*.leetcode.com/*' --exclude 'https://*.igdb.com/*' --exclude 'https://*.indeed.com/*' --exclude 'https://*.konghq.com/*' --exclude 'https://*.tableau.com/*' --exclude 'https://*.careerbuilder.com/*' --exclude 'https://*.phind.com/*' --exclude 'https://*.zenrows.com/*'
          output: /tmp/out.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: PR comment with Broken Links
        if: env.lychee_exit_code != 0
        uses: thollander/actions-comment-pull-request@v2.5.0
        with:
          filePath: /tmp/out.md
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
