name: Check for broken links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run DeadFinder
        uses: hahwul/deadfinder@1.3.4
        id: broken-link
        with:
          command: sitemap
          target: https://freeforgeeks.com/sitemap.xml or https://freeforgeeks.com/#/sitemap.xml

      - name: Output Handling
        run: echo '${{ steps.broken-link.outputs.output }}'
